version: '3.3'

services:
  api-gateway:
    hostname: api-gateway
    image: api-gateway:0.0.1
    networks:
      - rezervin-network-backend
    expose:
      - 8762
    ports:
      - 8762:8762
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
    entrypoint: [ "java","-jar","app.jar" ]

networks:
  rezervin-network-backend: